-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 01:41:03 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_callcenter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_callcenter` ;

-- -----------------------------------------------------
-- Schema bd_callcenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_callcenter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_callcenter` ;

-- -----------------------------------------------------
-- Table `bd_callcenter`.`Partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_callcenter`.`Partidos` (
  `id_partido` INT NOT NULL AUTO_INCREMENT,
  `nombre_partido` VARCHAR(150) NOT NULL,
  `imagen_partido` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_partido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_callcenter`.`Personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_callcenter`.`Personas` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(150) NOT NULL,
  `apellido_paterno` VARCHAR(150) NOT NULL,
  `apellido_materno` VARCHAR(150) NOT NULL,
  `nombre_completo` VARCHAR(250) NOT NULL,
  `direccion` TEXT NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `id_partido` INT NOT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `fk_Personas_Partidos_idx` (`id_partido` ASC),
  CONSTRAINT `fk_Personas_Partidos`
    FOREIGN KEY (`id_partido`)
    REFERENCES `bd_callcenter`.`Partidos` (`id_partido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_callcenter`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_callcenter`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(250) NOT NULL,
  `apellidos` VARCHAR(250) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(250) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_callcenter`.`Tipos_Cartas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_callcenter`.`Tipos_Cartas` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_callcenter`.`Textos_Cartas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_callcenter`.`Textos_Cartas` (
  `id_texto` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_carta` INT NOT NULL,
  `texto_carta` TEXT NOT NULL,
  PRIMARY KEY (`id_texto`),
  INDEX `fk_Textos_Cartas_Tipos_Cartas1_idx` (`id_tipo_carta` ASC),
  CONSTRAINT `fk_Textos_Cartas_Tipos_Cartas1`
    FOREIGN KEY (`id_tipo_carta`)
    REFERENCES `bd_callcenter`.`Tipos_Cartas` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
